name: Docker CI

on:
  push:
    banches: [ "master" ]

permissions:
  contents: read
  packages: wri

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: cloud-dashboard:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: save docker image
        run: docker save cloud-dashboard:latest -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: download docker image
        run: actions/download-artifcat@v4
        with:
          name: docker-image

      - name: load docker image
        run: docker run -d -p 5000:5000 --name test-container cloud-dashboard:latest

      - name: wait for health check
        run: |
          for i in {1..10}; do
            if curl -f http://localhost:5000/health; then
              echo "App is healthy"
              exit 0
            fi
            echo "Waiting..."
            sleep 2
          done
          echo "App failed health check"
          exit 1

      - name: Show container logs on failure
        if: failure()
        run: docker logs test-container
      
      - name: Cleanup
        if: always()
        run: docker rm -f test-container

  
  publish:
    runs-on: ubuntu-latest
    needs: test
  
    steps:
      - name: download docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: load docker image
        run: docker load -i image.tar

      - name: log in to GCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: tag image
        run: |
          docker tag cloud-dashboard:latest ghcr.io/jagsdd/cloud-homelab-dashboard:latest

      - name: push image
        run: |
          docker push ghcr.io/jagsdd/cloud-homelab-dashboard:latest











        

